- config/tests/jest/setup/setupTests.js
- package.json
- yarn.lock
Install @testing-library/jest-dom for additional testing utilities
> Install @testing-library/jest-dom

- src/shared/components/ui/Form/Select/Select.test.js
Update Form/Select/Select.test.js because of promise unhandled error
> Update Form/Select/Select.test.js - unhandled promise error

- README.md
Had to update the readme to fit the latest changes related to CI/CD
> Update README.md CI/CD

- src/shared/components/global/Logo/Logo.test.js
Refactor Logo tests to RTL
https://landingi.atlassian.net/browse/GRO-2509?atlOrigin=eyJpIjoiOTU5ZGY1ZTJjOTNkNGRmYThkOGVlNTFiYTk5ZDY2OGEiLCJwIjoiaiJ9
> [GRO-2509]Refactor Logo tests to RTL

- package.json
- src/shared/components/ui/Dropdown/Dropdown.test.js
https://landingi.atlassian.net/jira/software/projects/EDI/boards/90?assignee=612e7839b78590007105d94b&selectedIssue=EDI-1075
Fixed console.error in dropdown tests
> [EDI-1075][editor]Dropdown tests - fixed console.error

- src/components/Alert/Alert.js
- src/components/Alert/Alert.test.js
> [LAND-42]Update Alert test

- src/components/Avatar/Avatar.js
- src/components/Avatar/Avatar.test.js
> [LAND-42]Update Avatar test

- src/components/Backdrop/Backdrop.test.js
> [LAND-42]Update Backdrop  test

- src/components/ColorLine/ColorLine.test.js
> [LAND-42]Update ColorLine test

- src/components/ColorNumber/ColorNumber.js
- src/components/ColorNumber/ColorNumber.test.js
- src/components/Notification/Notification.js
- src/components/Notification/Notification.test.js
- src/components/ProgressBar/ProgressBar.js
Rewrite test for Notification and Alert
> [LAND-42]Notification and ColorNumber test update

- src/components/Input/Input.js
- src/components/Input/Input.test.js
> [LAND-42]Rewrite Input test to RTL

- src/components/Search/Search.js
- src/components/Searcher/Searcher.js
- src/components/Searcher/Searcher.test.js
Rewrite Searcher tests to RTL.
> [LAND-42]Rewrite Searcher tests to RTL.

- src/components/DropdownSelect/DropdownSelect.test.js
Rewrite DropdownSelect tests to RTL.
> [LAND-42]Rewrite DropdownSelect tests to RTL

- src/components/Form/Input/MaskedInput.js
- src/components/Form/Input/MaskedInput.test.js
Test for form wrapper of masked input
> [LAND-42]Masked input test

- dist/components/BlockSection/BlockSection.d.ts
- package.json
- src/components/BlockSection/BlockSection.tsx
https://landingi.atlassian.net/browse/LAND-85
BlockSection types fixed.
> [LAND-85]Fix BlockSection types

- package.json
> [APP-1347]New build v3.1.82

- package.json
- pnpm-lock.yaml
> [APP-1413]Update packages

- dist/components/Dot/Dot.d.ts
- package.json
- src/components/Dot/Dot.tsx
https://landingi.atlassian.net/browse/APP-1721
Updated `label` prop type in the Dot component.
> [APP-1721]Update Dot component

- package.json
- pnpm-lock.yaml
Due to storybook build error on cd i updated some package to work with cd build
> Storybook fix build

- package.json
- src/components/Back/Back.stories.tsx
- rewrite Back story so it's more customizable
- get rid of deprecated components:  ComponentMeta, ComponentStory
story demo:
https://github.com/landingi/ui-kit/assets/61820384/3b4a3d32-b47a-4dd6-b778-ced1dd5c9233
> [LAND-246]Back story

- src/components/Loader/Loader.stories.tsx
- src/components/Loader/Loader.tsx
- src/components/MonthRangePicker/MonthRangePicker.test.tsx
- src/components/Spacer/Spacer.stories.tsx
- src/components/Spacer/Spacer.tsx
- src/components/StatsBadge/StatsBadge.stories.tsx
- src/components/StatsBadge/StatsBadge.tsx
Add stories to: Loader, Spacer and StatsBadge [LAND-287] [LAND-308] [LAND-311]
Loader: 
https://github.com/landingi/ui-kit/assets/67641152/f460c6d8-3488-4a12-bd3c-7939d753e3e1
Spacer:
https://github.com/landingi/ui-kit/assets/67641152/32fa9d36-05a1-452e-b92f-3398004d88f0
StatsBadge: 
https://github.com/landingi/ui-kit/assets/67641152/ad9eaa31-fa95-4988-9d29-8a01dab6615d
[LAND-287]: https://landingi.atlassian.net/browse/LAND-287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LAND-308]: https://landingi.atlassian.net/browse/LAND-308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LAND-311]: https://landingi.atlassian.net/browse/LAND-311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …
> [GRO-5054] Add stories to: Loader, Spacer and StatsBadge

- .github/workflows/cd.yml
- .github/workflows/ci.yml
cI.yml
1. pnpm/action-setup@v2.4.0 -> v3.0.0
cd.yml
1. pnpm/action-setup@v2.4.0 -> v3.0.0
> [OP-1123] Bumped deprecated GHAs
